# Generated by Django 4.0.5 on 2022-09-18 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_for', models.CharField(default='Unknown', max_length=40, null=True)),
                ('amount', models.BigIntegerField()),
                ('transaction_type', models.CharField(choices=[('added', 'added'), ('debit', 'debit')], max_length=20)),
                ('category', models.CharField(choices=[('uncategorized', 'uncategorized'), ('food', 'food'), ('snacks', 'snacks'), ('drinks', 'drinks'), ('travel', 'travel'), ('needs', 'needs'), ('salary', 'salary'), ('income', 'income')], default='uncategorized', max_length=15)),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
