# Generated by Django 4.0.5 on 2022-08-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_for', models.CharField(default='Unknown', max_length=40, null=True)),
                ('amount', models.BigIntegerField()),
                ('transaction_type', models.CharField(choices=[('added', 'added'), ('debit', 'debit')], max_length=20)),
                ('category', models.CharField(choices=[('food', 'food'), ('snacks', 'snacks'), ('drinks', 'drinks'), ('uncategorized', 'uncategorized'), ('travel', 'travel'), ('needs', 'needs'), ('salary', 'salary'), ('income', 'income')], default='uncategorized', max_length=15)),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
