# Generated by Django 4.1.2 on 2022-10-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('loan-repayment', 'loan-repayment'), ('loan-given', 'loan-given'), ('uncategorized', 'uncategorized'), ('food', 'food'), ('travel', 'travel'), ('salary', 'salary'), ('income', 'income'), ('invoice-payment', 'inovice-payment')], default='uncategorized', max_length=15),
        ),
    ]
