# Generated by Django 5.0.4 on 2024-04-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseApp', '0004_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('fd', 'FD'), ('food', 'Food'), ('grocery', 'Grocery'), ('income', 'Income'), ('invoice_payment', 'Invoice-Payment'), ('loan_given', 'Loan-Given'), ('loan_repayment', 'Loan-Repayment'), ('rd', 'RD'), ('recharge', 'Recharge'), ('salary', 'Salary'), ('shopping', 'Shopping'), ('travel', 'Travel'), ('uncategorized', 'Uncategorized')], default='food', max_length=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid_for',
            field=models.CharField(default='Unknown', max_length=40),
        ),
    ]
