# Generated by Django 5.0.4 on 2024-04-04 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseApp', '0005_alter_transaction_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.BigIntegerField(default=0, verbose_name='Transaction Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('fd', 'FD'), ('food', 'Food'), ('grocery', 'Grocery'), ('income', 'Income'), ('invoice_payment', 'Invoice-Payment'), ('loan_given', 'Loan-Given'), ('loan_repayment', 'Loan-Repayment'), ('rd', 'RD'), ('recharge', 'Recharge'), ('salary', 'Salary'), ('shopping', 'Shopping'), ('travel', 'Travel'), ('uncategorized', 'Uncategorized')], default='food', max_length=15, verbose_name='Transaction Category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid_for',
            field=models.CharField(default='Unknown', max_length=40, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('added', 'Credit'), ('debit', 'Debit')], default='debit', max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
