TRANSACTION_CATEGORY_CHOICE_FD='fd'
TRANSACTION_CATEGORY_CHOICE_FOOD='food'
TRANSACTION_CATEGORY_CHOICE_GROCERY='grocery'
TRANSACTION_CATEGORY_CHOICE_INCOME='income'
TRANSACTION_CATEGORY_CHOICE_INVOICE_PAYMENT='invoice_payment'
TRANSACTION_CATEGORY_CHOICE_LOAN_GIVEN='loan_given'
TRANSACTION_CATEGORY_CHOICE_LOAN_REPAYMENT='loan_repayment'
TRANSACTION_CATEGORY_CHOICE_RD='rd'
TRANSACTION_CATEGORY_CHOICE_RECHARGE='recharge'
TRANSACTION_CATEGORY_CHOICE_SALARY='salary'
TRANSACTION_CATEGORY_CHOICE_SHOPPING='shopping'
TRANSACTION_CATEGORY_CHOICE_TRAVEL='travel'
TRANSACTION_CATEGORY_CHOICE_UNCATEGORIZED='uncategorized'

TRANSACTION_CATEGORY_CHOICES=(
    (TRANSACTION_CATEGORY_CHOICE_FD,'FD'),
    (TRANSACTION_CATEGORY_CHOICE_FOOD,'Food'),
    (TRANSACTION_CATEGORY_CHOICE_GROCERY,'Grocery'),
    (TRANSACTION_CATEGORY_CHOICE_INCOME,'Income'),
    (TRANSACTION_CATEGORY_CHOICE_INVOICE_PAYMENT,'Invoice-Payment'),
    (TRANSACTION_CATEGORY_CHOICE_LOAN_GIVEN,'Loan-Given'),
    (TRANSACTION_CATEGORY_CHOICE_LOAN_REPAYMENT,'Loan-Repayment'),
    (TRANSACTION_CATEGORY_CHOICE_RD,'RD'),
    (TRANSACTION_CATEGORY_CHOICE_RECHARGE,'Recharge'),
    (TRANSACTION_CATEGORY_CHOICE_SALARY,'Salary'),
    (TRANSACTION_CATEGORY_CHOICE_SHOPPING,'Shopping'),
    (TRANSACTION_CATEGORY_CHOICE_TRAVEL,'Travel'),
    (TRANSACTION_CATEGORY_CHOICE_UNCATEGORIZED,'Uncategorized'),
)

TRANSACTION_TYPE_CHOICE_CREDIT='added'
TRANSACTION_TYPE_CHOICE_DEBIT='debit'

TRANSACTION_TYPE_CHOICES=(
    (TRANSACTION_TYPE_CHOICE_CREDIT,'Credit'),
    (TRANSACTION_TYPE_CHOICE_DEBIT,'Debit')
)